trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/test/unit'
- task: CmdLine@2
  inputs:
    script: |
      echo YAML pipline
      dir=$(pwd)
      du -sh $dir
- task: whitesource.WhiteSource-bolt-staging.bolt.wss.WhiteSource@20
  inputs:
    projectName: 'MavenYAML'
    configuration: 'resolveAllDependencies=false'
