trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm1@1
  inputs:
    command: 'install'
    workingDir: 'npm'
- task: Npm2@1
  inputs:
    command: 'install'
    workingDir: 'npm/handlers'
- task: Npm3@1
  inputs:
    command: 'install'
    workingDir: 'npm/public'
- task: Npm4@1
  inputs:
    command: 'install'
    workingDir: 'npm/routes'
- task: Npm5@1
  inputs:
    command: 'install'
    workingDir: 'npm/services'
- task: Npm6@1
  inputs:
    command: 'install'
    workingDir: 'npm/test/unit'
- task: CmdLine@2
  inputs:
    script: |
      echo YAML pipline
      dir=$(pwd)
      du -sh $dir
- task: WhiteSource@20
  inputs:
    projectName: 'MavenYAML'
