# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/handlers'
    displayName: '1 npm install'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/public'
    displayName: '2 npm instal'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/routes'
    displayName: '3 npm instal'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/services'
    displayName: '4 npm install'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/test/unit'
    displayName: '5 npm instal'
- task: CmdLine@2
  inputs:
    script: |
      dir=$(pwd)
        du -sh $dir
- task: WhiteSource@20
  inputs:
    projectName: 'scan Big Project'
