# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm/handlers'
- task: WhiteSource@20
  inputs:
    cwd: 'npm/handlers'
    projectName: 'scan npm/handlers dir'
